### ISSUE TITLE
Command Line Usage still force user to use dialogs

### ISSUE THREAD

**Issue by muchamaciek** [hn-88/OCVWarp#23]
The tool is amazing, and now works way much better still does not allow to be used as a commandline tool for images for two reasons:

- it does not allow to run on sequences starting not from 0 (so starting with frame 600 is not possible), so you cannot run it in batches, or in case of fail, you have to run it again from 0
- when using a single picture input (so literally written number, like: "Frame_00569.png" it opens a dialog with a question if it is a sequence or not. It should be possible to force him do the image which is not a sequence.

**Comment by hn-88** [comment]
> it does not allow to run on sequences starting not from 0 (so starting with frame 600 is not possible)

Yes, that is true, that is a limitation of the implementation in opencv.

> when using a single picture input (so literally written number, like: "Frame_00569.png" it opens a dialog with a question if it is a sequence or not. It should be possible to force him do the image which is not a sequence.

This should not happen. Will check.

**Comment by hn-88** [comment]
@muchamaciek please check out the latest [release v 4.01](https://github.com/hn-88/OCVWarp/releases/tag/v4.01)

**Comment by hn-88** [comment]
Need to test on Linux - on Google Cloud Shell, errors like
```
./ocvwarp OCVWarp.ini hanu0018.jpg "hanuW.jpg"
Output codec type: NULL
Invalid SOS parameters for sequential JPEG
OpenCV: FFMPEG: tag 0x65706a6d/'mjpe' is not found (format 'image2 / image2 sequence')'

(ocvwarp:2932): GStreamer-CRITICAL **: 03:45:19.474: gst_element_make_from_uri: assertion 'gst_uri_is_valid (uri)' failed
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1492) open OpenCV | GStreamer warning: OpenCV backend does not support passed FOURCC value
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1274) close_ OpenCV | GStreamer warning: No source in GStreamer pipeline. Ignore
[ERROR:0] global ../modules/videoio/src/cap.cpp (415) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) ../modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/hnsmoney/hanuW.jpg in function 'icvExtractPattern'


Could not open the output video for write:
```

**Comment by hn-88** [comment]
```
./ocvwarp OCVWarp.ini hanu0018.jpg hanuW0018.jpg
```
solves the problem. If input has zeros/numbers in filename, output filename also should have!
